<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="OIOLedsageDokumentSamlingHentService" targetNamespace="urn:oio:skat:emcs:ws:1.0.1" xmlns="" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:struct="urn:oio:skat:emcs:ws:1.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:documentation>OIO-udgave af tilsvarende forretningsservice.  Servicen benyttes til af forespørge på ledsagedokumenter.</xs:documentation>
  </xs:annotation>
  <wsdl:types>
    <xsd:schema targetNamespace="urn:oio:skat:emcs:ws:1.0.1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:struct="urn:oio:skat:emcs:ws:1.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:include schemaLocation="urn/oio/skat/emcs/ws/1_0_1/OIOLedsageDokumentSamlingHentInterface.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="OIOLedsageDokumentSamlingHentServiceRequest">
    <wsdl:part element="struct:OIOLedsageDokumentSamlingHent_I" name="Request"/>
  </wsdl:message>
  <wsdl:message name="OIOLedsageDokumentSamlingHentServiceResponse">
    <wsdl:part element="struct:OIOLedsageDokumentSamlingHent_O" name="Response"/>
  </wsdl:message>
  <wsdl:portType name="OIOLedsageDokumentSamlingHentServicePortType">
    <wsdl:operation name="getOIOLedsageDokumentSamlingHent">
      <wsdl:input message="struct:OIOLedsageDokumentSamlingHentServiceRequest"/>
      <wsdl:output message="struct:OIOLedsageDokumentSamlingHentServiceResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OIOLedsageDokumentSamlingHentServiceBinding" type="struct:OIOLedsageDokumentSamlingHentServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getOIOLedsageDokumentSamlingHent">
      <soap:operation soapAction="getOIOLedsageDokumentSamlingHent" style="document"/>
      <wsdl:input>
        <soap:body namespace="http://skat.dk/begrebsmodel/2009/01/15/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body namespace="http://skat.dk/begrebsmodel/2009/01/15/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OIOLedsageDokumentSamlingHentService">
    <wsdl:port binding="struct:OIOLedsageDokumentSamlingHentServiceBinding" name="OIOLedsageDokumentSamlingHentServicePort">
      <soap:address location="http://localhost/EMCS_OIOLedsageDokumentSamlingHent/OIOLedsageDokumentSamlingHentServicePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>