<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="OIOForsendelseAfbrydelseBeskedSamlingHentService" targetNamespace="urn:oio:skat:emcs:ws:1.0.1" xmlns="" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:struct="urn:oio:skat:emcs:ws:1.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:documentation/>
  </xs:annotation>
  <wsdl:types>
    <xsd:schema targetNamespace="urn:oio:skat:emcs:ws:1.0.1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:struct="urn:oio:skat:emcs:ws:1.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:include schemaLocation="urn/oio/skat/emcs/ws/1_0_1/OIOForsendelseAfbrydelseBeskedSamlingHentInterface.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="OIOForsendelseAfbrydelseBeskedSamlingHentServiceRequest">
    <wsdl:part element="struct:OIOForsendelseAfbrydelseBeskedSamlingHent_I" name="Request"/>
  </wsdl:message>
  <wsdl:message name="OIOForsendelseAfbrydelseBeskedSamlingHentServiceResponse">
    <wsdl:part element="struct:OIOForsendelseAfbrydelseBeskedSamlingHent_O" name="Response"/>
  </wsdl:message>
  <wsdl:portType name="OIOForsendelseAfbrydelseBeskedSamlingHentServicePortType">
    <wsdl:operation name="getOIOForsendelseAfbrydelseBeskedSamlingHent">
      <wsdl:input message="struct:OIOForsendelseAfbrydelseBeskedSamlingHentServiceRequest"/>
      <wsdl:output message="struct:OIOForsendelseAfbrydelseBeskedSamlingHentServiceResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OIOForsendelseAfbrydelseBeskedSamlingHentServiceBinding" type="struct:OIOForsendelseAfbrydelseBeskedSamlingHentServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getOIOForsendelseAfbrydelseBeskedSamlingHent">
      <soap:operation soapAction="getOIOForsendelseAfbrydelseBeskedSamlingHent" style="document"/>
      <wsdl:input>
        <soap:body namespace="http://skat.dk/begrebsmodel/2009/01/15/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body namespace="http://skat.dk/begrebsmodel/2009/01/15/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OIOForsendelseAfbrydelseBeskedSamlingHentService">
    <wsdl:port binding="struct:OIOForsendelseAfbrydelseBeskedSamlingHentServiceBinding" name="OIOForsendelseAfbrydelseBeskedSamlingHentServicePort">
      <soap:address location="http://localhost/WebServices-ED_OIOForsendelseAfbrydelseBeskedSamlingHent-context-root/OIOForsendelseAfbrydelseBeskedSamlingHentServicePortTypeImplService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>